MvcKutuphane/Controllers/DuyuruController.cs
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DbKutuphaneEntities5 db = new DbKutuphaneEntities5();
        public ActionResult Index()
        {
            var degerler=db.TBL_DUYURULAR.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }

        [HttpPost]

        public ActionResult DuyuruEkle(TBL_DUYURULAR p)
        {
            db.TBL_DUYURULAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DuyuruSil(int id)
        {
            var deger = db.TBL_DUYURULAR.Find(id);
            db.TBL_DUYURULAR.Remove(deger);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DuyuruDetay(TBL_DUYURULAR p)
        {
            var duyuru = db.TBL_DUYURULAR.Find(p.ID);
            return View("DuyuruDetay",duyuru);
        }

        public ActionResult DuyuruGuncelle(TBL_DUYURULAR p)
        {
            var duyuru = db.TBL_DUYURULAR.Find(p.ID);
            duyuru.Kategori = p.Kategori;
            duyuru.Icerik = p.Icerik;
            duyuru.Tarih = p.Tarih;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBL_DUYURULAR

@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}




@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-top:15px"></div>
    <div class="form-group">
        @Html.LabelFor(p => p.ID)
        @Html.TextBoxFor(p => p.ID, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        @Html.LabelFor(p => p.Kategori)
        @Html.TextBoxFor(p => p.Kategori, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        @Html.LabelFor(p => p.Icerik)
        @Html.TextBoxFor(p => p.Icerik, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        @Html.LabelFor(p => p.Tarih)
        @Html.TextBoxFor(p => p.Tarih, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>

}

MvcKutuphane/Views/Duyuru/DuyuruEkle.cshtml
@model MvcKutuphane.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form method="post">
    <div style="margin-bottom:15px; margin-top:15px;"></div>
    <label>Duyuru Kategorisi</label>
    @Html.TextBoxFor(x => x.Kategori, "", new { @class = "form-control" })
    <div style="margin-bottom:15px; margin-top:15px;"></div>

    <label>Duyuru İçerik</label>
    @Html.TextBoxFor(x => x.Icerik, "", new { @class = "form-control" })
    <div style="margin-bottom:15px; margin-top:15px;"></div>

    <label>Duyuru Tarih</label>
    @Html.TextBoxFor(x => x.Tarih, "", new { @class = "form-control" })
    <div style="margin-bottom:15px; margin-top:15px;"></div>


    <button type="submit" class="btn btn-primary">Duyuru Ekle</button>
</form>

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBL_DUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<table class="table table-bordered">
    <tr style="background-color:rgb(252,178,22)">
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.Kategori</td>
            <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
            <td><a class="btn btn-danger"  href="/Duyuru/DuyuruSil/@x.ID">Sil</a></td>
            <td><a class="btn btn-default" href="/Duyuru/DuyuruDetay/@x.ID">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/DuyuruEkle/" class="btn btn-primary">Duyuru Ekle</a>