MvcKutuphane/Controllers/LoginController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcKutuphane.Controllers
{
    public class LoginController : Controller
    {
        DbKutuphaneEntities5 db = new DbKutuphaneEntities5();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(TBL_UYELER p)
        {
            var bilgiler = db.TBL_UYELER.FirstOrDefault(x => x.UyeMail == p.UyeMail && x.UyeSifre == p.UyeSifre);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.UyeMail, false);
                Session["Mail"] = bilgiler.UyeMail;
                //Session["ID"] = bilgiler.ID.ToString();
                //Session["AdSoyad"] = bilgiler.UyeAdSoyad.ToString();
                //Session["KullaniciAd"] = bilgiler.UyeKullaniciAd.ToString();
                //Session["Sifre"] = bilgiler.UyeSifre.ToString();
                //Session["Telefon"] = bilgiler.UyeTelefon.ToString();
                //Session["Okul"] = bilgiler.UyeOkul.ToString();
                return RedirectToAction("Index", "Panel");
            }
            else
            {
                return View();
            }
        }
        }
    }

MvcKutuphane/Views/Login/Index.cshtml
@{
        Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Giriş Formu</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Art Sign Up Form Responsive Widget, Audio and Video players, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates,
		Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design" />
    <link href="~/weblogin/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/weblogin/css/fontawesome-all.css" rel="stylesheet" />
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
</head>

<body>
    <h1>Kütüphane Giriş Formu</h1>
    <div class=" w3l-login-form">
        <h2>Giriş Yap</h2>

            @using (Html.BeginForm("Index","Login",FormMethod.Post)){
            <div class=" w3l-form-group">
                <label>Kullanıcı Mail:</label>
                <div class="group">
                    <i class="fas fa-user"></i>
                    <input type="text" class="form-control" placeholder="Mailiniz" required="required" name="UyeMail" />
                </div>
            </div>
            <div class=" w3l-form-group">
                <label>Şifre:</label>
                <div class="group">
                    <i class="fas fa-unlock"></i>
                    <input type="password" class="form-control" placeholder="Şifre" required="required" name="UyeSifre" />
                </div>
            </div>
            <div class="forgot">
                <a href="#">Şifrenimi unuttun ?</a>
                <p><input type="checkbox">Beni Hatırla</p>
            </div>
            <button type="submit">Login</button>
            }
        <p class=" w3l-register-p">Hesabın Yokmu?<a href="/KayitOl/Index/" class="register"> Kayıt Ol</a></p>
    </div>
    <footer>
        <p class="copyright-agileinfo"> &copy; 2025 MVC Projesi Bütün Hakları Saklıdır | W3layouts <a href="http://w3layouts.com">Tarafından Tasarlandı</a></p>
    </footer>

</body>

</html>