MvcKutuphane/Controllers/OduncKitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class OduncKitapController : Controller
    {
        // GET: OduncKitap

        DbKutuphaneEntities5 db = new DbKutuphaneEntities5();
        public ActionResult Index()
        {
            var liste = db.TBL_HAREKET.Where(x=>x.IslemDurum==false).ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult OduncVer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(TBL_HAREKET p)
        {
            db.TBL_HAREKET.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Odunciade(int id)
        {
            var odn = db.TBL_HAREKET.Find(id);
            DateTime d1 = DateTime.Parse(odn.KitapİadeTarih.ToString());
            DateTime d2 = Convert.ToDateTime((DateTime.Now.ToShortDateString()));
            TimeSpan d3 = d2-d1; //TimeSpan, iki DateTime nesnesi arasındaki zaman farkını verir.
            ViewBag.ceza = d3.TotalDays;
            return View("Odunciade", odn);
        }

        public ActionResult OduncKitapGuncelle(TBL_HAREKET p)
        {
            var hrkt = db.TBL_HAREKET.Find(p.HAREKETID);
            hrkt.UyeGetirdigiTarih = p.UyeGetirdigiTarih;
            hrkt.IslemDurum = true;
            db.SaveChanges();
            return RedirectToAction("Index");

        }


    }
}

MvcKutuphane/Views/OduncKitap/Index.cshtml
@model  List<MvcKutuphane.Models.Entity.TBL_HAREKET>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}



<table class="table table-bordered">

    <tr cl>
        <th>Hareket ID</th>
        <th>Üye ID</th>
        <th>Kitap ID</th>
        <th>Personel ID</th>
        <th>Kitap Alış Tarih</th>
        <th>Kitap İade Tarih</th>
        <th>Kitap İade Al</th>
    </tr>
    @foreach (var x in Model)
    {

        <tr>
            <td>@x.HAREKETID</td>
            <td>@x.UYE</td>
            <td>@x.KITAP</td>
            <td>@x.PERSONEL</td>
            <td>@Convert.ToDateTime(x.KitapAlisTarih).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.KitapİadeTarih).ToString("dd/MM/yyyy")</td>
            <td><a class="btn btn-info" href="/OduncKitap/Odunciade/@x.HAREKETID">Kitap İade Al</a></td>
        </tr>
    }
</table>

MvcKutuphane/Views/OduncKitap/OduncVer.cshtml
@model MvcKutuphane.Models.Entity.TBL_HAREKET
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}




<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Üye ID</label>
        @Html.TextBoxFor(k => k.UYE, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.UYE, "",new {@class="text-danger"})
    <div style="margin-top:15px">
        <label>Kitap ID</label>
        @Html.TextBoxFor(k => k.KITAP, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KITAP, "", new { @class = "text-danger" })
    </div>
    <div style="margin-top:15px">
        <label>Personel ID</label>
        @Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.PERSONEL, "", new { @class = "text-danger" })
    </div>
        <div style="margin-top:15px">
            <label>Kitap Alış Tarih</label>
            <input type="text" class="form-control" name="KitapAlisTarih" value="@DateTime.Now.ToShortDateString()" />
        </div>
        <div style="margin-top:15px">
            <label>Kitap İade Tarih</label>
            <input type="text" class="form-control" name="KitapİadeTarih" value="@DateTime.Now.AddDays(7).ToShortDateString()"/>
        </div>
        <div style="margin-top:15px"></div>
        <button class="btn btn-info">Kitabı Ödünç Ver</button>
        <input  type="hidden" name="IslemDurum" value="False"/>
</form>

MvcKutuphane/Views/OduncKitap/Odunciade.cshtml
@model MvcKutuphane.Models.Entity.TBL_HAREKET
@{
    ViewBag.Title = "Odunciade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap İade Sayfası</h2>

@using (Html.BeginForm("OduncKitapGuncelle", "OduncKitap", FormMethod.Post))
{
    <div style="margin-top:15px"></div>
    <div class="form-group">
        <label>Hareket ID</label>
        @Html.TextBoxFor(p => p.HAREKETID, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>Kitap Adı</label>
        @Html.TextBoxFor(p => p.TBL_KİTAP.KitapAd, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>Üye Adı</label>
        @Html.TextBoxFor(p => p.TBL_UYELER.UyeAdSoyad, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>Personel Adı</label>
        @Html.TextBoxFor(p => p.TBL_PERSONEL.PersonelAdSoyad, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>Kitap Alış Tarih</label>
        @Html.TextBoxFor(p => p.KitapAlisTarih, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>İade Edilmesi Gereken Tarih</label>
        @Html.TextBoxFor(p => p.KitapİadeTarih, new { @class = "form-control" })
        <div style="margin-top:15px"></div>
        <label>İade Edilen Tarih</label>
        <input type="text" class="form-control" name="UyeGetirdigiTarih" value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Geç Gelen Gün Sayısı</label>
        <input type="text" class="form-control" id="GecTarih" value="@ViewBag.ceza" />
    </div>
    <div>
        <button class="btn btn-warning" href="/OduncKitap/Index/">Ödünç Kitabı Geri Al</button>
    </div>

}