MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap

        DbKutuphaneEntities5 db = new DbKutuphaneEntities5();
        public ActionResult Index()
        {
            var kitaplar = db.TBL_KİTAP.ToList();
            return View(kitaplar);
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from x in db.TBL_KATEGORİ.ToList()
                                         select new SelectListItem
                                         {
                                             Text=x.Ad,
                                             Value=x.ID.ToString()
                                         }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in db.TBL_YAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text=x.YazarAdSoyad,
                                               Value=x.ID.ToString()    
                                           } 
                                         ).ToList();
            ViewBag.dgr2=deger2;
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBL_KİTAP p)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //Dikkatli Bak Bu Kısıma!!!!
            var ktg = db.TBL_KATEGORİ.FirstOrDefault(k => k.ID == p.ID);
            var yzr = db.TBL_YAZAR.FirstOrDefault(y => y.ID == p.ID);

            p.TBL_KATEGORİ = ktg;
            p.TBL_YAZAR = yzr;
            
            db.TBL_KİTAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var ktp=db.TBL_KİTAP.Find(id);
            db.TBL_KİTAP.Remove(ktp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBL_KİTAP.Find(id);
            List<SelectListItem> deger1 = (from x in db.TBL_KATEGORİ.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Ad,
                                               Value = x.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in db.TBL_YAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.YazarAdSoyad,
                                               Value = x.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            return View("KitapGetir",ktp);
        }
        public ActionResult KitapGuncelle(TBL_KİTAP p)
        {     
            var ktp= db.TBL_KİTAP.Find(p.ID);
            ktp.KitapAd = p.KitapAd;
            ktp.KitapBasimYili = p.KitapBasimYili;
            ktp.KitapYayınEvi = p.KitapYayınEvi;
            ktp.KitapSayfaSayısı = p.KitapSayfaSayısı;
            ktp.KitapDurum = true;
            var ktg = db.TBL_KATEGORİ.Where(x => x.ID == p.TBL_KATEGORİ.ID).FirstOrDefault();
            var yzr = db.TBL_YAZAR.Where(x => x.ID == p.TBL_YAZAR.ID).FirstOrDefault();
            ktp.Kategori = ktg.ID;
            ktp.KitapYazar = yzr.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        
    }
}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBL_KİTAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}



@using (Html.BeginForm("Index","Kitap",FormMethod.Get))
{
    <div style="margin-top:15px;margin-bottom:15px">
        <input type="text" class="form-control" name="p" placeholder="Aranacak Kitabı Giriniz" /> 
        <div style="margin:10px"></div>
        <button class="btn btn-info" type="submit" value="Ara">Ara</button>
    </div>
}


<table class="table table-bordered">
    <tr style="background-color:rgb(16, 255, 0)">
        <th>ID</th>
        <th>Kitap Ad</th>
        <th>Kitap Yazarı</th>
        <th>Kitap Basım Yılı</th>
        <th>Kitap Yayın Evi</th>
        <th>Kitap Sayfa Sayısı</th>
        <th>Kitap Kategorisi</th>
        <th>Kitap Durumu</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.KitapAd</td>
            <td>@k.TBL_YAZAR.YazarAdSoyad</td>
            <td>@k.KitapBasimYili</td>
            <td>@k.KitapYayınEvi</td>
            <td>@k.KitapSayfaSayısı</td>
            <td>@k.TBL_KATEGORİ.Ad</td>
            <td>@k.KitapDurum</td>
            <td><a class="btn btn-danger" href="/Kitap/KitapSil/@k.ID">Sil</a></td>
            <td><a class="btn btn-success" href="/Kitap/KitapGetir/@k.ID">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Kitap/KitapEkle" class="btn btn-primary">Kitap Ekle</a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBL_KİTAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}




<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.KitapAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KitapAd, "",new { @class = "text-danger" })
    </div> 
    <div style="margin-top:15px">
        <label>Kitap Kategorisi</label>
        @Html.DropDownListFor(k => k.Kategori, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazarı</label>
        @Html.DropDownListFor(k => k.KitapYazar, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yayın Evi</label>
        @Html.TextBoxFor(k => k.KitapYayınEvi, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KitapYayınEvi, "", new {@class="text-danger"})
    </div>
    <div style="margin-top:15px">
        <label>Kitap Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.KitapSayfaSayısı, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KitapSayfaSayısı, "", new { @class = "text-danger" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Basım Yılı</label>
        @Html.TextBoxFor(k => k.KitapBasimYili, new { @class = "form-control" })
        @Html.ValidationMessageFor(k => k.KitapBasimYili, "", new { @class = "text-danger" })
    </div>
    <div style="margin-top:15px"></div>
    <button class="btn btn-info">Kitap Ekle</button>
    <input  type="hidden" name="KitapDurum" value="True"/>
</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBL_KİTAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div class="form-group">
        <div style="margin-top:15px">
            <label>Kitap ID</label>
            @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Kitap Adı</label>
            @Html.TextBoxFor(k => k.KitapAd, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Kategori</label>
            @Html.DropDownListFor(k => k.TBL_KATEGORİ.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Kitap Yazarı</label>
            @Html.DropDownListFor(k => k.TBL_YAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Basım Yılı</label>
            @Html.TextBoxFor(k => k.KitapBasimYili, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Yayın Evi</label>
            @Html.TextBoxFor(k => k.KitapYayınEvi, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px">
            <label>Sayfa Sayısı</label>
            @Html.TextBoxFor(k => k.KitapSayfaSayısı, new { @class = "form-control" })
        </div>
        <div style="margin-top:15px"></div>
            <button class="btn btn-success">Güncelle</button>
        </div>
        }